name: Run Selenium BDD Tests

on:
  schedule:
    - cron: 'H/15 * * * * / */15 * * * *'  # Runs every day at midnight
  push:
    branches:
      - main  # Optionally, run on every push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: mvn install

    - name: Run tests
      run: mvn test
