name: Daily Job

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8am IST daily
    - cron: '0 23 * * *' # Runs at 11pm IST daily.

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "Running daily job"
          # Add your script or command here
